### ISSUE TITLE
Redundant tool installation logic in cibuild.sh and Dockerfile

### ISSUE THREAD

**Issue by yamt** [apache/incubator-nuttx-testing#35]
cibuild.sh and docker/linux/Dockerfile have similar logic to install tools.
IMO, the Dockerfile should use "cibuild.sh -i" to install tools.

**Comment by btashton** [comment]
The dockerfile is much more efficient and is also designed using multistage builds so it can easily be broken up to Target specific arch.  It is almost half the size you get by using the shell script install.

**Comment by yamt** [comment]
you can use cibuild.sh in an intermediate stage and COPY files in the last stage. this way the final image size should be almost same.

**Comment by btashton** [comment]
This still means you have a single huge intermediate stage and you lose all build caching of the image since you cannot cache the intermediate steps of the build. This is a large cost when trying to test and add new changes to the image and why I structured it this way.

**Comment by yamt** [comment]
i agree the way the Dockerfile version works is neat.
but regardless of how good it is, IMO it's simpler to use a single copy (cibuild.sh) instead of two.

anyway it's just my opinion.
your opinion is more important as you are actually maintaining it.
i'm closing this.
