### ISSUE TITLE
nuttx-ci-linux is based on a non-LTS version of ubuntu

### ISSUE THREAD

**Issue by yamt** [apache/incubator-nuttx-testing#58]
nuttx-ci-linux is based on 19.10, which is not LTS.

if there's a reason to stick with the version, it should be documented.
(i couldn't find it)

otherwise, it's better to go with the LTS, 20.04.

**Comment by xiaoxiang781216** [comment]
Good point, with 20.04 we can install kconfig-frontend directly:
```
sudo apt-get install kconfig-frontends
```

**Comment by v01d** [comment]
I agree that we should target LTS releases. 18.04 (previous LTS) is still maintained though. Should we only consider latest LTS?

**Comment by btashton** [comment]
Let's move to 20.04 it's a one line change. I would rather not use the Ubuntu Kconfig build since we recommend all users use the one from tools and need to verify that build for other OS.
