### ISSUE TITLE
move content to main repo?

### ISSUE THREAD

**Issue by protobits** [apache/incubator-nuttx-testing#98]
I think we discussed this in the past and I believe it would make things quite simpler since changes in this repo will break CI until we update the other two repos to be in sync.

**Comment by xiaoxiang781216** [comment]
Yes, I propose before since the ci infrasttucture is simple and useful not only for github, but also for internal use.

**Comment by btashton** [comment]
Yeah it's also making it harder for me to test my runtime tests. As I cannot tweak/add configs.

**Comment by v01d** [comment]
I can give it a try later if the outstanding PRs in this repo are merged

**Comment by xiaoxiang781216** [comment]
We can migrate first, but shutdown this repo after all PR transfer to nuttx repo.

**Comment by btashton** [comment]
See this PR https://github.com/apache/incubator-nuttx/pull/3318

**Comment by v01d** [comment]
Should we kill this repo now?

**Comment by Ouss4** [comment]
We have those open PRs that we wouldn't want to lose.
Maybe we can save them as patches and create new ones in the OS repo.

**Comment by v01d** [comment]
Two are @btashton's, maybe he can verify if they are still valid and if so move them. The other one about LTP is by @ttnie, who does not appear to be active (I've pinged them recently in another related PR) so maybe we can port the PR to the main repo.

**Comment by btashton** [comment]
I have something that does the ltp work. I have this PR integrated in the functional test. I will put a PR up with this soon with the other test foundation.


As for the cygwin stuff I still want to get that in as well now that we have a minimal test set like so the build does not take forever.

**Comment by v01d** [comment]
Cool. So if you can open these PRs against the main repo later on we could already delete this repo, right?

**Comment by btashton** [comment]
This has been moved for awhile now, so I am going to close this out.
